### ISSUE TITLE
Add Example ? or update readme with main functions?

### ISSUE THREAD

**Issue by Saifallak** [eGust/epub-package.dart#2]
Add Example ? or update readme with main functions?

i have no idea how we can use this as no docs provided ,,
can you tell us the main functions at least and i will discover the rest ?

**Comment by eGust** [comment]
This package is still in a very early stage. I am working on my own [reader](https://github.com/eGust/epub-shelf.flutter) which depends on this project. It may still have bugs, and the API could change a lot to meet my own requirements. 
You can have a look of my reader which is already able to display the content, and the next task is to display toc. I will start working on it again maybe 1 or 2 weeks later. I will update the documentation after the toc part finished.

**Comment by Saifallak** [comment]
Great ,, I'll check it
